### ISSUE TITLE
ReferenceError: Buffer is not defined after updating to Angular 6

### ISSUE THREAD

**Issue by Sazeidya** [jacobwgillespie/b64u#1]
Hello,

I've updated my Angular application from Version 5.2 to 6.0.

After that, my application is crashing everytime I try to decode a base64url encoded string (like in a JWT payload).

Following error occurs in the browser console:

`ERROR Error: Uncaught (in promise): ReferenceError: Buffer is not defined
ReferenceError: Buffer is not defined
    at Function.decode (b64u.m.js:27)`

I've already done some research and other people also have this particular error after upgrading to Angular 6, but I couldn't find any reason why it is throwing the error. In Angular 5.2 everything worked fine.

A workaround I found is to insert the following line of code into your polyfills.ts:
`global.Buffer = global.Buffer || require('buffer').Buffer;`

Does anyone know what I need to do to get it work without the workaround above? Does this package need to be updated for Angular 6? I don't know what was changed in Angular 6.0 compared to Angular 5 so that this error is now thrown.

I appreciate any help or more information about this :)

Thanks and have a nice day!

**Comment by jacobwgillespie** [comment]
How is the application being bundled?  I would assume that the switch from 5.2 to 6.0 could have dropped a polyfill, depending on the bundling config.  Webpack, etc, should be handling `Buffer` in the browser.
